pipeline {
    agent any

    tools {
        maven "MAVEN"
    }

    stages {
        stage('Initialize') {
            steps {
                echo "PATH = ${env.M2_HOME}/bin:${env.PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
                dir("/var/lib/jenkins/workspace/New_demo/my-app") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
    }
    post {
        always {
            junit(
                allowEmptyResults: true,
                testResults: '**/test-reports/*.xml'
            )
        }
    }
}
